### PR TITLE
fix bug and IO mode improve

### PR DESCRIPTION
**Pull request by codesgeeking**
1, fix client mode bug : the first packet from client must be early than the first packet send to server, otherwise, it can't work well;
2, change the client mode thead mode: one io thread for client , multi io threads for server. now when request too many, it can't work;

### CODE REVIEW

**Comment by GreaterFire** [comment]
Thanks for your contributions! It's been long discussed that we do not need multiple threads.

**Comment by codingdie** [comment]
> Thanks for your contributions! It's been long discussed that we do not need multiple threads.

how about the bug  in client mode? when ssl hanshake with server finished early than the arrive for first client packet, the code in clientsession.cpp will close the socket because of lack Payload,  i think it will be better to wait for the first proxy packet arrive rather than force close

**Comment by codesgeeking** [comment]
how about the bug  in client mode? when ssl hanshake with server finished early than the arrive for first client packet, the code in clientsession.cpp will close the socket because of lack Payload,  i think it will be better to wait for the first proxy packet arrive rather than force close.

**Comment by codesgeeking** [comment]
> Thanks for your contributions! It's been long discussed that we do not need multiple threads.

how about the bug in client mode? when ssl hanshake with server finished early than the arrive for first client packet, the code in clientsession.cpp will close the socket because of lack Payload, i think it will be better to wait for the first proxy packet arrive rather than force close.

**Comment by GreaterFire** [comment]
@codesgeeking The code correctly handles your case

**Pull request closed without merging**
