### PR TITLE
add: added logger callback

### PR DESCRIPTION
**Pull request by ghost**
For those GUI applications handling logs from the kernel.
It's better to add an externel logger (callback) function.

Didn't fully check the whole codebase, please suggest any changes if needed.

### CODE REVIEW

**Comment by ghost** [comment]
These changes should not break the Windows CI.

**Comment by GreaterFire** [comment]
Thanks so much for your contribution! I do not have much time to review PRs in this project recently, but I'll do it as soon as possible.

**Comment by ghost** [comment]
Just force pushed another commit, which introduced a macro, `TROJAN_USE_EXTERNAL_LOGGER`

For now, this change will not affect existing applications if `TROJAN_USE_EXTERNAL_LOGGER` is not defined.

**Comment by GreaterFire** [comment]
I prefer calling the logger unconditionally.

**Comment by GreaterFire** [comment]
Feature manually pushed (https://github.com/trojan-gfw/trojan/commit/b70dd573ad1687217bfa19b93430f5d6830991fd).

**Comment by ghost** [comment]
Thanks

**Pull request closed without merging**
