### PR TITLE
Make auth an interface for more db options

### PR DESCRIPTION
**Pull request by llc1123**
mongodb and redis support coming soon

### CODE REVIEW

**Comment by GreaterFire** [comment]
I would like to re-architect the current authentication framework so that it can load dynamically linked objects. Does that sound good?

**Comment by llc1123** [comment]
I don't think we need that kind of flexibility. Even if you support a lot of kinds of DBs, the size of the binary is still rather small.

**Comment by GreaterFire** [comment]
@llc1123 The purpose is that so the authentication is decoupled from trojan itself. If we add a bunch of DB supports to trojan itself, it'll be 1) messy, both in terms of code and configuration, 2) not extensible, and 3) requiring a lot of dependencies. I'm highly against adding another or multiple dependencies to trojan.

**Comment by llc1123** [comment]
You mean using an external lib instead of static linked? It sounds good but how do you select which one to use and pass the params?

**Comment by GreaterFire** [comment]
Discussion settled elsewhere.

**Pull request closed without merging**
