### PR TITLE
Using multi-stage build to reduce image size

### PR DESCRIPTION
**Pull request by k4yt3x**
I've been working with docker/k8s recently and was looking for ways to reduce image size. I improved the trojan's Dockerfile while I was doing some experiments. This change reduces the image size from 11.1 MiB to 9.67 MiB.

References:
- https://docs.docker.com/develop/develop-images/multistage-build/
- https://www.youtube.com/watch?v=wGz_cbtCiEA

### CODE REVIEW

**Comment by wongsyrone** [comment]
Please sign the CLA

**Comment by k4yt3x** [comment]
@wongsyrone I did, not sure why it's not registering.

**Comment by wongsyrone** [comment]
LGTM, but someone else must approve.

**Comment by k4yt3x** [comment]
FYI:

image

This is as far as I'm gonna go.

**Review by Kellzhut — APPROVED** [review]

**Pull request merged**
