### PR TITLE
refactor and a new feature (NAT for UDP)

### LINKED ISSUE #350: [Feature Request] Support transparent proxy via iptables?
Can be used as trojan client as "transparent proxy gateway" using.

### PR DESCRIPTION
**Pull request by yuchting**
refactor: I changed the deriving arch, now the NATSession is derived by ClientSession, so a lot of duplicated codes can be removed.

new feature: I checked a lot codes of ss-redir and add a new feature, now "nat" mode can open a udp port and redirect tproxy message from iptables, you can review these "service.h/cpp", "udpforwardsession.h/cpp" files to check how.

this new feature has been test by me for some days, but it may has unpredictable bug.

### CODE REVIEW

**Review by wongsyrone — CHANGES_REQUESTED** [review]
NAK from me.
1. Huge changes, your should split it into multiple commits.
2. CI fails on most platforms except Linux.
3. You should talk with us before sending huge changes.

**Comment by yuchting** [comment]
@wongsyrone 

Thanks for reminding, I haven't cooperated with others in github before. So cool about this CI check!

Let me explain what I did.

Few days ago, I wanted to use trojan as transparent proxy, but it hasn't provided the udp redirect which provided by ss, so I just wanted to add this feature.

After reviewing trojan codes, I found a lot of duplicated code, so I decided to refactor firstly to remove those duplicated codes. so I did following changes:

[#refactor nat session and client session](https://github.com/trojan-gfw/trojan/pull/390/commits/2abed3d5b5469c010f465f6f7eaad0aa033d906a)

[#refactor forwardsession, removing a lot of duplicated codes](https://github.com/trojan-gfw/trojan/pull/390/commits/378ce6b2b20b39b0f2fee4c6611efebbda476562)

these 2 changes just are refactored by my programming experience, and it has a litter bug with NATSession after refactor, this bug I found when I'm adding new udp nat feature.

**so, should I request 2 PR for these 2 commits?**

**Comment by wongsyrone** [comment]
@GreaterFire will give the final decision.

**Comment by yuchting** [comment]
@wongsyrone 

after refactoring, I started to add new udp nat feature:

[#feature add a udp nat feature](https://github.com/trojan-gfw/trojan/pull/390/commits/1930bbf1a5aa742109926670723792c6ee920b05)

I think it's cannot be divided, it's a completed feature.

a lot of codes are inspired by ss-libev.

**Comment by yuchting** [comment]
@wongsyrone 

about the CI check, in Windows, maybe, it's a CI bug:
image

it reports boost version is too low, I haven't changed the project compiling options, just *.h/cpp file. Or something I missed?

In MacOS, it's my fault, I will check and fix them.

**Comment by yuchting** [comment]
in order to change the error commit author, I just reopened this PR.

**Comment by GreaterFire** [comment]
Thanks so much for your contribution! I do not have much time to review PRs in this project recently, but I'll do it as soon as possible.

**Comment by yuchting** [comment]
@GreaterFire 
Thanks for your great project, please don't hesitate to ask me about these PR commits.

**Comment by GreaterFire** [comment]
We do not have the plan to refactor the code. Can you only provide the UDP TPROXY feature without refactoring the code?

**Comment by yuchting** [comment]
@GreaterFire 

I'm so sad to know about you don't want to refactor to remove those duplicated codes.

I know there are some conflicts for your recent commits, actually I can merge that and then commit again.

The real reason I persist to refactor codes is not only I want to remove duplicated codes to avoid bugs, but also I did a big feature for trojan at these 2 weeks.

Here's what I did:
https://github.com/yuchting/trojan/wiki/Why-we-need-Pipeline-mode%3F
(tech design brief wiki is WIP).

and you can review my folk repo (dev branch):
https://github.com/yuchting/trojan/commits/dev

That's what I did a lot of refactors and optimizations.

of course, if you don't want to apply my new dev codes of new big feature, these codes I will use by my self in GPL license.

Finally, about this NAT udp feature, if you don't refactor all the same, you can check my 4 commits to know how, and of course, pull them and merge them by yourself easily.

[#feature add a udp nat feature](https://github.com/yuchting/trojan/commit/bba1b2e64240d34e426ef2061fdf244042d35ffc)
[#fixed the compiler error in MacOS](https://github.com/yuchting/trojan/commit/8de828acfd4d8ac4d3485c3e9e51306b30879c96)
[#fixed set the udp nat SO_REUSEADDR flag](https://github.com/yuchting/trojan/commit/5cb7e46658b0e126309838cc52ce70b3f2ea7923)
[#fixed the bug that udp status error](https://github.com/yuchting/trojan/commit/3f7cfe82c2387710f6e976e8e4a5f5c221845e16)

These codes are copied and refactor from ss-libev, not my idea.

**Comment by yuchting** [comment]
Here's a home page of my dev wiki:
https://github.com/yuchting/trojan/wiki

It explain what I did in recent 2 weeks and what I want to do next. 
Of course you can checkout my repo dev branch to test what I said and realized.

Thanks!

**Comment by GreaterFire** [comment]
Sure. It would be pretty nice of you if you can resolve the conflicts. Thanks!

**Comment by yuchting** [comment]
> Sure. It would be pretty nice of you if you can resolve the conflicts. Thanks!

sorry for missing your reply, I'm working for other big features, here's a summary:
https://github.com/yuchting/trojan/wiki

I will resolve them after I finish some points at these days.

**Comment by yuchting** [comment]
@GreaterFire 

I merged all codes, please review them and leave me a message if has any question.

**Comment by GreaterFire** [comment]
Thanks again for your contributions. I feel so sorry to inform you that I decide not to merge this gigantic change. The amount of change here makes it impossible (or too much work) to review the entire thing, from logic to code style, and make sure there aren't any hidden bugs. Thank you for your great work anyways, especially the TPROXY part. You may keep your change in your fork and make a note in the Wiki to point to your project in case anyone wants to use TPROXY.

**Pull request closed without merging**
