### PR TITLE
statically linked to MSVC runtime library

### PR DESCRIPTION
**Pull request by wongsyrone**
ref: https://cmake.org/cmake/help/v3.15/prop_tgt/MSVC_RUNTIME_LIBRARY.html

try to prevent similar issues like https://github.com/trojan-gfw/trojan/issues/145

### CODE REVIEW

**Comment by wongsyrone** [comment]
Please test before merging.

**Comment by GreaterFire** [comment]
@wongsyrone I'm OK with it if CI passes.

**Comment by wongsyrone** [comment]
CI error is caused by the centos-docker-image building command: https://github.com/trojan-gfw/centos-build-image/blob/master/Dockerfile#L17, we should change `runtime-link=shared` to `runtime-link=static` to let MSVC take the static library into account.

```
libboost_program_options-vc141-mt-x64-1_69.lib(value_semantic.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
libboost_program_options-vc141-mt-x64-1_69.lib(options_description.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
libboost_program_options-vc141-mt-x64-1_69.lib(positional_options.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
libboost_program_options-vc141-mt-x64-1_69.lib(cmdline.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
libboost_program_options-vc141-mt-x64-1_69.lib(convert.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
libboost_program_options-vc141-mt-x64-1_69.lib(variables_map.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
libboost_program_options-vc141-mt-x64-1_69.lib(utf8_codecvt_facet.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in authenticator.obj [D:\a\1\s\trojan.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc141-mt-s-x64-1_69.lib' [D:\a\1\s\trojan.vcxproj]
```

**Comment by wongsyrone** [comment]
I have another dirty way, just modify 'RuntimeLibrary' of 'Release|x64' in trojan.vcxproj to 'MultiThreaded' instead of 'MultiThreadedDLL' without CMakeLists changes, while it still requires building `runtime-link=static` Boost for Windows.

**Comment by GreaterFire** [comment]
After some consideration, I don't think we should statically link any C++ runtime...
What we can do is we can pack the runtime installer in the release.

**Comment by wongsyrone** [comment]
LGTM.

**Comment by klzgrad** [comment]
FYI Chrome on Windows is built with static CRT https://cs.chromium.org/chromium/src/build/config/win/BUILD.gn?l=468.

**Pull request closed without merging**
