### PR TITLE
do not use deprecated resolver overload for Boost >= 1.66.0

### PR DESCRIPTION
**Pull request by wongsyrone**
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by GreaterFire** [comment]
@wongsyrone I'll put this pr on hold, since we might perform a full boost upgrade.

**Comment by wongsyrone** [comment]
Agreed.

**Comment by GreaterFire** [comment]
We can add `BOOST_ASIO_NO_DEPRECATED` definition when compiling. Any use of deprecated functions or classes will be errored.

**Comment by GreaterFire** [comment]
close due to #87

**Pull request closed without merging**
