### PR TITLE
Let trojan support multi threads

### PR DESCRIPTION
**Pull request by xyanrch1024**
The main purpose of the RP is let server side support multi thread, and also fix the the issue#178.

### CODE REVIEW

**Comment by GreaterFire** [comment]
Thanks for your contribution! Could you fix the CI build error?

I might put this PR on hold since I don't know whether we really need this. Multi-threading can have various side effects and requires intensive testing before merging.

**Comment by wongsyrone** [comment]
Trojan is single-threaded now, you may start multiple processes when we get reuse_address and reuse_port working correctly.

**Comment by xyanrch1024** [comment]
Thanks for your reply. Yes, This RP is sometimes unstable when handle the signals, maybe I need investigate this if I have time. By the way I use boost：：thread  in cmake, but CI complain can't find  the thread.
Please feel free to close this RP.

**Comment by GreaterFire** [comment]
You'll almost certainly need to use [`strands`](https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/overview/core/strands.html) to avoid race conditions.

**Pull request closed without merging**
